# This file should contain everything to configure the workflow on a global scale.
fq_dir: "/mnt/md0/RGIcat_test/fqs"
results_dir: "/mnt/md0/RGIcat_test/results"
votus_fa: "/mnt/md0/RGIcat_test/vOTUs.fasta"
rgi_tab: "/mnt/md0/RGIcat_test/Predicted_AMG.txt"